name: Remove old artifacts

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'